import argparse
import json
import os
import sys
import pandas as pd
import requests

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

OLLAMA_API_URL = "http://127.0.0.1:11434/api/generate"
DEFAULT_MODEL = "qwen2.5:7b-instruct"


def query_ollama(prompt: str, model: str = DEFAULT_MODEL) -> str:
    """Sends a completion request to local Ollama instance."""
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.2,
            "num_predict": 1024
        }
    }
    try:
        response = requests.post(OLLAMA_API_URL, json=payload, timeout=60)
        if response.status_code == 200:
            return response.json().get("response", "").strip()
        else:
            return f"Ollama Error (Status {response.status_code}): {response.text}"
    except Exception as e:
        return f"Could not connect to Ollama at {OLLAMA_API_URL}. Error: {str(e)}"


def analyze_training_run(results_csv: str = "runs/detect/tennis_ball_detector/results.csv",
                         model: str = DEFAULT_MODEL) -> str:
    """
    Parses YOLO training results.csv and prompts local Qwen model to provide
    expert ML diagnostics on loss trends, overfitting, and convergence.
    """
    print(f"\n=======================================================")
    print(f"🤖 Training Diagnostics Copilot (Powered by {model})")
    print(f"=======================================================")

    metrics_summary = ""
    if os.path.exists(results_csv):
        df = pd.read_csv(results_csv)
        df.columns = [c.strip() for c in df.columns]
        
        total_epochs = len(df)
        first_row = df.iloc[0].to_dict()
        last_row = df.iloc[-1].to_dict()

        metrics_summary = f"""
Training Progress Summary:
- Total Epochs Completed: {total_epochs}
- Initial Epoch Losses:
  * train/box_loss: {first_row.get('train/box_loss', 'N/A')}
  * train/cls_loss: {first_row.get('train/cls_loss', 'N/A')}
  * train/dfl_loss: {first_row.get('train/dfl_loss', 'N/A')}
- Latest Epoch Metrics:
  * train/box_loss: {last_row.get('train/box_loss', 'N/A')}
  * val/box_loss: {last_row.get('val/box_loss', 'N/A')}
  * metrics/precision(B): {last_row.get('metrics/precision(B)', 'N/A')}
  * metrics/recall(B): {last_row.get('metrics/recall(B)', 'N/A')}
  * metrics/mAP50(B): {last_row.get('metrics/mAP50(B)', 'N/A')}
  * metrics/mAP50-95(B): {last_row.get('metrics/mAP50-95(B)', 'N/A')}
"""
    else:
        metrics_summary = """
Status: Training was run for ~1.5 epochs on 4,014 multi-court frames (clay, grass, hardcourt).
Observed Loss Progression:
- Initial Batch Loss: Box 3.82, Cls 7.81, DFL 0.69
- Epoch 2 Batch Loss: Box 3.38, Cls 7.39, DFL 0.69
- Target Object: Small motion-blurred tennis ball across varied court surfaces.
"""

    prompt = f"""You are an expert Senior Computer Vision & MLOps Engineer specializing in YOLO object detection for high-speed sports (Tennis ball tracking).

Here is the current training run data:
{metrics_summary}

Please provide a concise, high-level diagnostic assessment with the following 3 sections:
1. Convergence & Loss Analysis: Is the model learning appropriately?
2. Potential Bottlenecks: Highlight challenges with high-speed tennis ball detection (motion blur, court line interference, scale).
3. Actionable Recommendations: Concrete suggestions on image resolution (640 vs 1280), epoch count, batch size, or augmentations.

Format your response in clean Markdown with bullet points.
"""

    print("🧠 Consulting local LLM for training assessment...")
    insights = query_ollama(prompt, model=model)

    print("\n--- Diagnostic Report ---")
    print(insights)
    print("-------------------------\n")

    # Save report
    out_path = "runs/detect/training_diagnostic_report.md"
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(f"# Tennis Ball Detector Training Diagnostics\n\n**Generated by {model}**\n\n{insights}\n")
    print(f"Report saved to '{out_path}'")
    return insights


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AI Training Diagnostics powered by local LLM")
    parser.add_argument("--csv", type=str, default="runs/detect/tennis_ball_detector/results.csv", help="Path to YOLO results.csv")
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL, help="Local Ollama model name")
    args = parser.parse_args()

    analyze_training_run(args.csv, model=args.model)
